name: Deploy AWS Welcome App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.767397806650 }}:role/GitHubActionsDeploymentRole
          aws-region: us-east-1

      - name: Zip Lambda function
        run: |
          cd lambda
          zip -r ../lambda.zip .

      - name: Upload Lambda code to S3
        run: |
          aws s3 cp lambda.zip s3://welcomeapp-lambda-code-bucket/lambda.zip

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation.yaml \
            --stack-name WelcomeAppStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              LambdaS3Bucket=welcomeapp-lambda-code-bucket \
              LambdaS3Key=lambda.zip

      - name: Get API Gateway URL from CloudFormation Output
        id: get_apigw_url
        run: |
          url=$(aws cloudformation describe-stacks \
            --stack-name WelcomeAppStack \
            --query "Stacks[0].Outputs[?OutputKey=='ApiGatewayInvokeUrl'].OutputValue" \
            --output text)
          echo "API_GATEWAY_URL=$url" >> $GITHUB_ENV

      - name: Replace API placeholder in frontend
        run: |
          sed -i "s|YOUR_API_GATEWAY_INVOKE_URL_HERE|${API_GATEWAY_URL}|g" web-app/index.html

      - name: Upload frontend to S3
        run: |
          aws s3 sync web-app/ s3://welcomeapp-static-website-bucket/ --delete

      - name: Print website URL
        run: |
          echo "Static Website: http://welcomeapp-static-website-bucket.s3-website-us-east-1.amazonaws.com"
          echo "API Gateway URL: $API_GATEWAY_URL"
